#### Fernando Amaral 
#### chi square

In [2]:
# chi2_contingency because we have 2 categories
import numpy as np
from scipy.stats import chi2_contingency

In [3]:
# Creating the matrix with the data and running the test
novela = np.array([[19, 6], [43, 32]])
novela

array([[19,  6],
       [43, 32]])

In [4]:
# second value is the pvalue
# p value is greater than 0.05 no evidence of significant difference 
# (null hypothesis): no significant difference
chi2_contingency(novela)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

In [5]:
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [6]:
# now p-value less than 0.05, we can reject the null hypothesis in favor of the alternative hypothesis: 
# there is significant difference
chi2_contingency(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))